USE SlibraryAutomationPrograming

CREATE TABLE tblTurler
(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TURAD VARCHAR(30) UNIQUE


)

CREATE TABLE tblYayinevleri
(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
AD VARCHAR(50) UNIQUE,
ADRES VARCHAR(50),
TEL VARCHAR(11)

)





CREATE TABLE tblUyeler
(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ADSOYAD VARCHAR(30),
CINSIYET VARCHAR(1),
DOGUMTARIHI DATE,
TEL VARCHAR(11),
MAIL VARCHAR(40),
UYELIKTARIHI DATE,
UYELIKTIPI INT,
TCNO VARCHAR(11),
MESLEK VARCHAR(30),
EGITIMDURUMU INT, 
CEZADURUMU BIT,


)

CREATE TABLE tblYazarlar
(
ID  INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
ADSOYAD VARCHAR(30),
CINSIYET VARCHAR(1),
DOGUMTARIHI DATE,
TEL VARCHAR(11),
MAIL VARCHAR(40),
TURID INT FOREIGN KEY REFERENCES tblTurler(ID) ON DELETE CASCADE,



)
CREATE TABLE tblKitaplar
(
ISBN VARCHAR(13) NOT NULL PRIMARY KEY,
AD VARCHAR(100),
SAYFASAYISI INT,
STOK INT,
TURID INT FOREIGN KEY REFERENCES tblTurler(ID) ON DELETE CASCADE,
YAYINEVIID INT FOREIGN KEY REFERENCES tblYayinevleri(ID) ON DELETE CASCADE, 
YAZARID INT FOREIGN KEY REFERENCES tblYazarlar(ID)


)

CREATE TABLE tblOduncler
(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
UYEID INT FOREIGN KEY REFERENCES tblUyeler(ID) ON DELETE CASCADE,
KITAPISBN VARCHAR(13) FOREIGN KEY REFERENCES tblKitaplar(ISBN) ON DELETE CASCADE,
VERILISTARIHI DATE,
TESLIMTARIHI DATE,
IPTAL BIT,


)
USE SlibraryAutomationPrograming
INSERT INTO tblOduncler (UYEID,KITAPISBN,IPTAL) VALUES 
(5,'456321',0)

