--********************************* DATABASE OLUSTURULDU
--CREATE DATABASE Kutuphane_Projesi
USE Kutuphane_Projesi
-- *************************Kutuphaneye kayýtlý uyelerin tablosu olusturuldu
CREATE TABLE tblUyeler(

ID INT IDENTITY(1,1) NOT NULL,
UYEADI VARCHAR(30) NOT NULL,
UYESOYAD VARCHAR(30) NOT NULL,
UYETC CHAR(11) NOT NULL,
UYETEL CHAR(10) NOT NULL,
UYEMAIL VARCHAR(50) NOT NULL,
PRIMARY KEY(ID),
)
--*************************KUTUPHANE ILK UYE OLUSTURULDU
INSERT INTO tblUyeler
VALUES
('RECEP','CELIMLI','43243243243','5348859432','recep@hotmail.com')




--*********************** KÝTAP TURLERI EKLENDI
CREATE TABLE tblTurler(

ID INT IDENTITY(1,1) NOT NULL,
TURAD VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
)

--************************* KITAP TURLERINE VERI EKLENDI

INSERT INTO tblTurler
VALUES 
('TARIH'),('PISKOLOJI'),('TIP'),('FIZIK'),('MATEMATIK')

--************************** YAZARLARIN BÝLGÝLERÝ EKLENDI

CREATE TABLE tblYazarlar
(
ID INT IDENTITY(1,1) NOT NULL,
YAZARAD VARCHAR(30) NOT NULL,
YAZARSOYAD VARCHAR(30) NOT NULL,
YAZARCINSIYET CHAR(1) NOT NULL,
YAZARDOGUMTARIHI VARCHAR(10),
YAZARTEL CHAR(10),
YAZARMAIL VARCHAR(30),
PRIMARY KEY(ID),
)

--************************* ILK YAZAR VERISI GIRILDI

INSERT INTO tblYazarlar 
VALUES 
('YAZARRECEP','CELIMLI','E','11.11.1998','54648911','RECEPMAIL')

--************************** YAYINEVI BILGILERI GIRILDI
CREATE TABLE tblYayinevleri
(
ID INT IDENTITY(1,1) NOT NULL,
YAYINEVIADI VARCHAR(30) NOT NULL,
YAYINEVIADRESI VARCHAR(MAX),
YAYINEVITELEFONNUMARASI CHAR(10) NOT NULL,
PRIMARY KEY(ID),
)

--*********************** ÝLK YAYIN EVLERI GIRILDI
INSERT INTO tblYayinevleri
VALUES
('ERMAK','ÝSTANBUL','45645678'),('HASIL','BÝLECÝK','45645688')


--************************* KUTUPHANE KÝTAP BÝLGÝSÝ OLUSTUURULDU
CREATE TABLE tblKitaplar(

ID INT IDENTITY(1,1) NOT NULL,
KITAPADI VARCHAR(50) NOT NULL,
KITAPSAYFASAYISI INT NOT NULL,
KITAPSTOKADEDI INT NOT NULL,
TURID INT NOT NULL,
YAZARID INT NOT NULL,
YAYINEVIID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(TURID) REFERENCES tblTurler(ID),
FOREIGN KEY(YAZARID) REFERENCES tblYazarlar(ID),
FOREIGN KEY(YAYINEVIID) REFERENCES tblYayinevleri(ID),
)

--************************* KUTUPHANE ILK ODUNC KÝTAP BÝLGÝSÝ OLUSTUURULDU
CREATE TABLE tblOdunc(
ID INT IDENTITY(1,1) NOT NULL,
UYEID INT NOT NULL,
KITAPID INT NOT NULL,
ODUNCVERILMETARIHI VARCHAR(10),
TESLIMEDILMESIGEREKENTARIH VARCHAR(10),
TESLIMTARIHI VARCHAR(10),
PRIMARY KEY(ID),
FOREIGN KEY(UYEID) REFERENCES tblUyeler(ID),
FOREIGN KEY(KITAPID) REFERENCES tblKitaplar(ID),
)


